FROM prizm

RUN apk add --no-cache --virtual .build-deps \
 outils-md5 \
 cmake \
 &&  /usr/local/openresty/luajit/bin/luarocks install luacov \
 &&  /usr/local/openresty/luajit/bin/luarocks install busted

COPY . /etc/nginx/prizm-build

RUN cd /etc/nginx/prizm-build \
    && busted
